# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script: yarn install

audit/devel:
  stage: test
  script: yarn audit
  allow_failure: true

audit/master:
  stage: test
  script: yarn audit
  allow_failure: false
  only:
    - master

lint:
  stage: test
  script: yarn lint
  allow_failure: true
  when: always

build/devel:
  stage: build
  script: yarn build
  artifacts:
    untracked: true
    expire_in: 30 days
  except:
    - master

build/master:
  stage: build
  script: yarn build
  artifacts:
    untracked: true
  only:
    - master

pages:
  stage: build
  script: yarn docs
  after_script:
    - mv docs public
  artifacts:
    untracked: false
    paths:
      - public
    expire_in: 30 days

deploy:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build/master
  stage: deploy
  script:
    - npm publish
  only:
    - master
