name: Audits

on: [push]

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Audits
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: audit
