name: Audit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: audit
      continue-on-error: true
