name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn
      uses: Borales/actions-yarn@v2.1.0
    - name: Install
      run : yarn --frozen-lockfile
    - name: Build
      run : yarn build
    - name: Pack
      run : yarn pack
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: '*.tgz'
        # Directory containing files to upload
        path: .
