# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: Borales/actions-yarn@v2.1.0
      with:
        frozen-lockfile: true
    - name: Build docs
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: docs
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: docs
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
